source "http://rubygems.org"
gem "jekyll", "~>0.10"
gem "jekyll-less", "~>0.0.4"
gem "jekyll-categories", "0.0.2"
gem "jekyll-minimagick", "0.0.3"
gem "RedCloth", "~>4.2"
gem "therubyracer"
gem "rake-pipeline"
gem "rake-pipeline-web-filters"
gem "uglifier"